language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: pip install tox-travis
script: tox
notifications:
  email: false
  hipchat:
    rooms:
      secure: mTOlrhISOy8FSwtJQRJ4XuUg74ZXuovHUtP0XaFDuJvHv/mCf/uXfjCybanJSFQd/lNVHK3WwXcetopYHjmE9vgxWTweCfYGoudstDchfcjQd2fd+HXDJQGW7q9e2QO+Xj5a1sowhAwHqX+tisd/SRgn2Kd10+qVNqimlweJzlSqOkANY06hkLvWJpSGVMwQWyPUcI8u0GwNX5IhObAUbF9YbGsouEbXDx1t2Z0Ja5VglMvGHEBByymUaBEqHu6hGvFeO2ptyRTQWJc9YjoVc5YJvNYAbhCYn8fYjp7wDK3aFxDaodTr9ppV6LFD2OrAjq8i+x+l6e9/0Av5UxZsOiO6BkwweqVB9W/MmXywxkD0nFqvLlvZQri79NNPUUirPSYhhDOK9FvhcEDhnnCCKyau76TXWql4HVFlR08A6gG23llziT4KI/XzXaGMXKCKKRz1T/WYOvkEWC8qutTEw0dbid7neQkiIxGWpEBJwC4gMFBRZTGSULEL3+su/toVWRVAo8E6fGL1NosHBU93g7QxvKnZRPI8B6Tebpd1UvgPt+aEgPS4mbN0InwM9Wkko2wZNk7Sc/FiLcSDW5ZAAyUcPtuomA30KWTW1/94GTY5hdsjF3ch+k7lXFeGNp24Q6YHvtxhyTPIOFJz1+cHNU7qwyV6rSzguBcFE5v9iUc=
